version: "2.2"

services:
  web:
    build: 
      context: ./
      dockerfile: ./Dockerfileweb
    # image: php:8.0-apache
    ports:
      - "54322:80"
    restart: always
    volumes:
      - ./src:/var/www/html

  db:
    # image: mysql:5
    build: 
      context: ./
      dockerfile: ./Dockerfiledb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Teste
    ports:
      - "33066:3306"
    restart: always
