version: "2.2"

services:
  web:
    build: ./DockerfileWeb
    # image: php:8.0-apache
    ports:
      - "54322:80"
    restart: always
    volumes:
      - ./web:/var/www/html

  database:
    image: mysql:5
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Teste
    ports:
      - "33066:3306"
    restart: always
